---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-swift-openstack-org-v1beta1-swift
  failurePolicy: Fail
  name: mswift-v1beta1.kb.io
  rules:
  - apiGroups:
    - swift.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swifts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-swift-openstack-org-v1beta1-swiftproxy
  failurePolicy: Fail
  name: mswiftproxy-v1beta1.kb.io
  rules:
  - apiGroups:
    - swift.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swiftproxies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-swift-openstack-org-v1beta1-swift
  failurePolicy: Fail
  name: vswift-v1beta1.kb.io
  rules:
  - apiGroups:
    - swift.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swifts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-swift-openstack-org-v1beta1-swiftproxy
  failurePolicy: Fail
  name: vswiftproxy-v1beta1.kb.io
  rules:
  - apiGroups:
    - swift.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swiftproxies
  sideEffects: None
