apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/operator-type: non-standalone
  name: swift-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SwiftProxy is the Schema for the swiftproxies API
      displayName: Swift Proxy
      kind: SwiftProxy
      name: swiftproxies.swift.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: SwiftRing is the Schema for the swiftrings API
      displayName: Swift Ring
      kind: SwiftRing
      name: swiftrings.swift.openstack.org
      specDescriptors:
      - description: Enabled - Whether SwiftRing service should be deployed and managed
        displayName: Enabled
        path: enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: Swift is the Schema for the swifts API
      displayName: Swift
      kind: Swift
      name: swifts.swift.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: swiftProxy.tls
      - description: Enabled - Whether SwiftRing service should be deployed and managed
        displayName: Enabled
        path: swiftRing.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: swiftRing.tls
      version: v1beta1
    - description: SwiftStorage is the Schema for the swiftstorages API
      displayName: Swift Storage
      kind: SwiftStorage
      name: swiftstorages.swift.openstack.org
      version: v1beta1
  description: OpenStack Swift operator
  displayName: Swift operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Swift
  - Object Storage
  links:
  - name: Swift Operator
    url: https://github.com/openstack-k8s-operators/swift-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
